// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcfZfvlWG6La-fuxWi-gVox7DIiON6wwA',
    appId: '1:110640032902:web:f060114f52a0671567b507',
    messagingSenderId: '110640032902',
    projectId: 'most-64840',
    authDomain: 'most-64840.firebaseapp.com',
    storageBucket: 'most-64840.firebasestorage.app',
    measurementId: 'G-MG80NL1846',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7P9jI7QnZrDPYZnzLKrS7-faRqDuaczA',
    appId: '1:110640032902:android:7adaecd3a5a6caf967b507',
    messagingSenderId: '110640032902',
    projectId: 'most-64840',
    storageBucket: 'most-64840.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9XKtApMl-szMFOtoVdSMJAdyMQ2akCYc',
    appId: '1:110640032902:ios:d0f47d192847179767b507',
    messagingSenderId: '110640032902',
    projectId: 'most-64840',
    storageBucket: 'most-64840.firebasestorage.app',
    iosBundleId: 'com.example.test2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9XKtApMl-szMFOtoVdSMJAdyMQ2akCYc',
    appId: '1:110640032902:ios:d0f47d192847179767b507',
    messagingSenderId: '110640032902',
    projectId: 'most-64840',
    storageBucket: 'most-64840.firebasestorage.app',
    iosBundleId: 'com.example.test2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcfZfvlWG6La-fuxWi-gVox7DIiON6wwA',
    appId: '1:110640032902:web:7bca93ede3a0c02067b507',
    messagingSenderId: '110640032902',
    projectId: 'most-64840',
    authDomain: 'most-64840.firebaseapp.com',
    storageBucket: 'most-64840.firebasestorage.app',
    measurementId: 'G-RT67L857ZV',
  );
}
