// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEHWaLm4Zc_y4IBF021UwkE59es_m0f5o',
    appId:
        '1:150393919593:web:YOUR_WEB_APP_ID', // Remplacez par votre Web App ID
    messagingSenderId: '150393919593',
    projectId: 'most-3a4db',
    authDomain: 'most-3a4db.firebaseapp.com',
    storageBucket: 'most-3a4db.firebasestorage.app',
    databaseURL:
        'https://most-3a4db-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEHWaLm4Zc_y4IBF021UwkE59es_m0f5o',
    appId: '1:150393919593:android:20bf060ba36f81390d6af8',
    messagingSenderId: '150393919593',
    projectId: 'most-3a4db',
    databaseURL:
        'https://most-3a4db-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'most-3a4db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEHWaLm4Zc_y4IBF021UwkE59es_m0f5o',
    appId:
        '1:150393919593:ios:YOUR_IOS_APP_ID', // Remplacez par votre iOS App ID
    messagingSenderId: '150393919593',
    projectId: 'most-3a4db',
    storageBucket: 'most-3a4db.firebasestorage.app',
    databaseURL:
        'https://most-3a4db-default-rtdb.asia-southeast1.firebasedatabase.app',
    iosBundleId: 'com.example.most_secure',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEHWaLm4Zc_y4IBF021UwkE59es_m0f5o',
    appId:
        '1:150393919593:ios:YOUR_MACOS_APP_ID', // Remplacez par votre macOS App ID
    messagingSenderId: '150393919593',
    projectId: 'most-3a4db',
    storageBucket: 'most-3a4db.firebasestorage.app',
    databaseURL:
        'https://most-3a4db-default-rtdb.asia-southeast1.firebasedatabase.app',
    iosBundleId: 'com.example.most_secure',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEHWaLm4Zc_y4IBF021UwkE59es_m0f5o',
    appId:
        '1:150393919593:web:YOUR_WINDOWS_APP_ID', // Remplacez par votre Windows App ID
    messagingSenderId: '150393919593',
    projectId: 'most-3a4db',
    authDomain: 'most-3a4db.firebaseapp.com',
    storageBucket: 'most-3a4db.firebasestorage.app',
    databaseURL:
        'https://most-3a4db-default-rtdb.asia-southeast1.firebasedatabase.app',
  );
}
